# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lotte Chemist
tagline:          Chemistry
url:              http://lottechemist.com
paginate:         1
baseurl:          /
author:
  name:           Lotte Chemist
  email:          charlotte@cfranklin.com

# Custom vars
version:          1.0.0
github:
